### ISSUE TITLE
PoC (was 'mvp') progress tracking

### ISSUE THREAD

**Issue by wintermute-cell** [wintermute-cell/cowboy-gorl#3]
> branch `mvp` was renamed to `poc` as Proof of Concept is a more fitting description here.

This issue exists for the purpose of tracking progress of the test implementation on the `poc` branch.
Details on how things are to be implemented may be scattered across various places, for example my notebook. I will most likely have shared screenshots/pictures tho :)

> [!NOTE]  
> The code in the `poc` branch contains `// NOTE: ...` comments, describing problems with the current codebase.

- [ ] add basic game over state when fuel/coal reaches 0
- [x] add obstacle alerts/decision. this could be just rockslides, and a dynamite resource could be auto crafted using iron.
- [ ] add a health bar to visualize train condition for now. make health decrease on rockslide obstacles if blowing it up fails.
- [ ] add 0 train health as a game over condition
- [x] add worker assignment. for now, the pops number is a constant 44, and a dynamic subgroup of these could be assigned to different tasks. number of 'repair-workers' could increase train health regen (but increase iron consumption ofc)

**Comment by wintermute-cell** [comment]
the current `poc` branch implementation has revealed enough issues that can be worked on, after completing these, a new `poc` implementation is required.
